# Generated by Django 2.1.7 on 2019-07-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_mapping', '0004_remove_accountmapping_mandators'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandator',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_mapping.AccountMapping'),
        ),
    ]
