# Generated by Django 2.1.7 on 2019-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mapping', '0006_auto_20190706_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandator',
            name='logo_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mandator',
            name='theme',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
